### ISSUE TITLE
eet wont build due to incompatible liberty.a archive

### ISSUE THREAD

**Issue by daschewie** [kakaroto/e17#1] opened 2013-03-20 05:00 UTC
I am trying to compile e17 for the first time by running the script: 

> ./devs/kakaroto/build_ps3efl.sh

It is failing to compile eet, with the following error in the logs:

> Making all in bin
> make[3]: Entering directory `/home/user/Documents/e17/eet/src/bin'
>   CC     eet_main.o
> eet_main.c: In function 'do_eet_encode':
> eet_main.c:278:8: warning: unused variable 'size' [-Wunused-variable]
>   CCLD   eet
> /usr/local/ps3dev/ppu/lib/gcc/powerpc64-ps3-elf/4.7.0/../../../../powerpc64-ps3-elf /bin/ld: skipping incompatible /usr/local/ps3dev/ppu/lib/libiberty.a when searching for -liberty
> /usr/local/ps3dev/ppu/lib/gcc/powerpc64-ps3-elf/4.7.0/../../../../powerpc64-ps3-elf/bin/ld: skipping incompatible /usr/local/ps3dev/ppu/lib/libiberty.a when searching for -liberty
> /usr/local/ps3dev/ppu/lib/gcc/powerpc64-ps3-elf/4.7.0/../../../../powerpc64-ps3-elf/bin/ld: cannot find -liberty
> collect2: error: ld returned 1 exit status
> make[3]: *** [eet] Error 1
> make[3]: Leaving directory`/home/user/Documents/e17/eet/src/bin'
> make[2]: **\* [all-recursive] Error 1
> make[2]: Leaving directory `/home/user/Documents/e17/eet/src'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory`/home/user/Documents/e17/eet'
> make: **\* [all] Error 2

There is a copy of liberty.a under /usr/local/ps3dev/ppu/lib

I have the latest ps3toolchain/psl1ght from https://github.com/ps3dev/ps3toolchain
and RSXGL from https://github.com/gzorin/RSXGL

My environment variables are:

> Set up the environment.
> export PS3DEV=/usr/local/ps3dev
> export PSL1GHT=$PS3DEV
> 
> Set up the path.
> export PATH=$PATH:$PS3DEV/bin
> export PATH=$PATH:$PS3DEV/ppu/bin
> export PATH=$PATH:$PS3DEV/spu/bin

I am building under LinuxMint 14.

Thanks,
daschewie

**Comment by kakaroto** [comment] 2013-03-28 04:28
As discussed on IRC. The problem was that libiberty.a was an x86 binary and not a ppc64 binary, which was the cause for the "incompatible library" error.
Could be a ps3toolchain issue or an issue with your system (which shouldn't affect the ps3toolchain anyways).
As such, I am closing this issue since it doesn't seem to be coming from the efl itself.
Thanks for giving it a try! :)

**Closed as completed by kakaroto** 2013-03-28 04:28 UTC

**Comment by daschewie** [comment] 2013-03-28 04:33
I was able to get past the issue with the updated libiberty.a file. Thank you so much for the assistance.

**Comment by Spork-Schivago** [comment] 2013-10-30 21:57
Where did you find the updated libiberty.a file?
